version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    entrypoint: ./entrypoints/app-entrypoint.sh
    volumes:
    - ./application:/application
    - public-files:/application/public
    depends_on:
      - db
    ports:
      - "9000:9000"
    env_file: .env
      
  db:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    env_file: .env

  redis:
    image: redis:alpine

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - ./application:/application
    env_file: .env
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  web:
    build:
      context: .
      dockerfile: ./docker/webserver/Dockerfile
    depends_on:
      - app
      - db
    ports:
      - "3000:3000"
    volumes:
      - public-files:/application/public:ro

volumes:
  db_data:
  application:
  public-files: